version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3

  frontend:
    build: .
    ports:
      - "8080:80" 
    depends_on:
      - web

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "8081:80"
    depends_on:
      - frontend
